version: "3.1"
services:
  db:
    image: postgres
    restart: always
    container_name: "postgres"
    volumes:
      - /home/pavel/docker_sessions/docker_unik/docker_compose_2/csv/:/var/lib/postgresql/docker-entrypoint-initdb.d/
      - /home/pavel/docker_sessions/docker_unik/docker_compose_2/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "spark"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
        - "1234:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    tty: true

  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    volumes:
      - /home/pavel/docker_sessions/docker_unik/docker_compose_2/script/:/new/
      - /home/pavel/docker_sessions/docker_unik/docker_compose_2/driver/:/driver/
    environment: 
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker1:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  spark-worker2:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
